services:
    cabot.profilgauche.listener:
        class: cabot\profilgauche\event\listener
        arguments:
            - '@request'
            - '@template'
            - '@language'
            - '@user'
        tags:
            - { name: event.listener }
